s = input('Digite algo: ')
print(f'O tipo primitivo deste valor é: {type(s)}')
print(f'É alfa numérico?{s.isalnum()}')
print(f'É alfabético?{s.isalpha()}')
print(f'É um número? {s.isnumeric()}')
print(f'Está em letra maiúscula?{s.isupper()}')
print(f'É imprimível?{s.isprintable()}')
print(f'É composto de espaços?{s.isspace()}')
print(f'Está capitalizado? {s.istitle()}')
